import manifest from '@/data/images.json'

export interface ResponsiveImage {
  src: string
  srcSet: string
  width: number
  height: number
}

/**
 * Responsive variants of every photo, generated by `npm run images`.
 *
 * Spread an entry onto an <img> and add a `sizes` describing the slot it fills;
 * the browser then picks a file matched to the device instead of always pulling
 * the largest. Do not edit by hand — regenerate it.
 */
export const IMAGES: Record<string, ResponsiveImage> = manifest

export type ImageName = keyof typeof manifest
